### ISSUE TITLE
Error when trying to build "could not determine executable to run"

### ISSUE THREAD

**Issue by dustmop** [izfaruqi/boxed-chirps#1]
Error seems to be originating from npx or postcss. Not sure if it's a configuration issue on my end, project staleness, or incompatible versions of npm / npx. Any advice, work-around, or guidance on debugging would be much appreciated.

Already ran `npm install` and it finished without error.

```
> npm run build.css

0 verbose cli ]
1 info using npm@8.5.0
2 info using node@v16.14.2
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/Users/dustmop/.nvm/versions/node/v16.14.2/lib/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/Users/dustmop/git/boxed-chirps/.npmrc Completed in 0ms
10 timing config:load:project Completed in 3ms
11 timing config:load:file:/Users/dustmop/.npmrc Completed in 2ms
12 timing config:load:user Completed in 2ms
13 timing config:load:file:/Users/dustmop/.nvm/versions/node/v16.14.2/etc/npmrc Completed in 1ms
14 timing config:load:global Completed in 2ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 14ms
19 timing npm:load:configload Completed in 14ms
20 timing npm:load:setTitle Completed in 15ms
21 timing config:load:flatten Completed in 2ms
22 timing npm:load:display Completed in 3ms
23 verbose logfile /Users/dustmop/.npm/_logs/2022-03-29T18_16_43_647Z-debug-0.log
24 timing npm:load:logFile Completed in 5ms
25 timing npm:load:timers Completed in 0ms
26 timing npm:load:configScope Completed in 0ms
27 timing npm:load Completed in 39ms
28 silly logfile start cleaning logs, removing 1 files
29 timing command:exec Completed in 7ms
30 verbose stack Error: could not determine executable to run
30 verbose stack     at getBinFromManifest (/Users/dustmop/.nvm/versions/node/v16.14.2/lib/node_modules/npm/node_modules/libnpmexec/lib/get-bin-from-manifest.js:17:23)
30 verbose stack     at exec (/Users/dustmop/.nvm/versions/node/v16.14.2/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:115:15)
30 verbose stack     at async module.exports (/Users/dustmop/.nvm/versions/node/v16.14.2/lib/node_modules/npm/lib/cli.js:66:5)
31 verbose pkgid postcss@8.3.5
32 verbose cwd /Users/dustmop/git/boxed-chirps
33 verbose Darwin 18.7.0
34 verbose argv "/Users/dustmop/.nvm/versions/node/v16.14.2/bin/node" "/Users/dustmop/.nvm/versions/node/v16.14.2/lib/node_modules/npm/bin/npm-cli.js" "exec" "--" "postcss" "./src/templating/template.css" "-o" "./build/templating/compiled.purged.min.css"
35 verbose node v16.14.2
36 verbose npm  v8.5.0
37 error could not determine executable to run
38 verbose exit 1
39 timing npm Completed in 207ms
40 verbose code 1
41 error A complete log of this run can be found in:
41 error     /Users/dustmop/.npm/_logs/2022-03-29T18_16_43_647Z-debug-0.log
```

**Comment by izfaruqi** [comment]
Thanks for reporting! I'll take a look ASAP.
